config/routes.rb
Rails.application.routes.draw do
  



  root 'static_pages#home'


get 'provider/dashboard/panelist', to: 'provider/dashboard#panelist', as: 'provider_panelist'
get 'provider/dashboard/panelist/view_enrolee/:enrolee_id', to: 'provider/dashboard#view_provider_enrolee', as: 'view_provider_enrolee'


get 'enrolees/:enrolee_id/show_dependants_group', to: 'insurer/enrolees#show_dependants', as: 'show_dependants_group'

namespace :provider do 

  resources :claims do 
    member do 
        get 'addService'
        get 'preview'
        get 'submit'
    end
  end
end
  
  get 'provider/enrolees/panelist', to: 'provider#enrolees', as: 'provider_enrolees'
  get 'insurer/enrolees/quicksearch', to: 'insurer/enrolees#quicksearch', as: 'insurer_enrolees_quicksearch'
  get 'insurer/enrolees/data_upload', to: 'insurer/enrolees#data_upload', as: 'insurer_enrolees_data_upload'
  get 'insurer/dependants/data_upload', to: 'insurer/dependants#data_upload', as: 'insurer_dependants_data_upload'
  post 'insurer/enrolees/populatedb', to: 'insurer/enrolees#populatedb', as: 'insurer_enrolees_populatedb'
  post 'insurer/dependants/populatedb', to: 'insurer/dependants#populatedb', as: 'insurer_dependants_populatedb'

namespace :insurer do 
  resources :enrolees do 
    member do 
      get 'addDependant'
      get 'preview'
    end

  end
  resources :plans
  resources :companies
  resources :dependants
  resources :claims do
    member do  
      get 'addService'
      get 'submit'
      get 'preview'
      get 'vet'
      post 'submit_vetted'
      get 'invoice_generation'
    end
  end
end


  resources :services
  
  devise_for :providers, path: 'providers', controllers: {sessions: 'providers/sessions', registrations: 'providers/registrations'}
  devise_for :insurers, path: 'insurers', controllers: { sessions: 'insurers/sessions', registrations: 'insurers/registrations'}


  #static pages routes
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'

  get 'claims/invoice/generate_pdf', to: 'insurer/claims#generate_invoice', as: 'generate_claim_invoice_pdf'



  # Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  #dashboard pages

  get 'insurer/dashboard/index', to: 'insurer/dashboard#index', as: 'insurer_dashboard'

  get 'provider/dashboard/index', to: 'provider/dashboard#index', as: 'provider_dashboard'
    
  get 'static_pages/dashboard', to: 'static_pages#dashboard', as: 'dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if insurer_signed_in? 
      flash[:success] = "Welcome to your dashboard"
      redirect_to insurer_dashboard_path
    elsif provider_signed_in?
      flash[:success] = "Welcome to your dashboard"
    else

    end
  end

  def about
  end

  def contact
  end

  def dashboard
    if insurer_signed_in? 
      @enrolees = current_insurer.enrolees.limit(10)
      flash[:success] = "Welcome to your dashboard"
      redirect_to insurer_dashboard_path
    elsif provider_signed_in?

      flash[:success] = "Welcome to your dashboard"
      redirect_to provider_dashboard_path
    else

    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/dashboard.html.erb
<h2> Welcome to your dashboard</h2>
<p> Do have some fun while here</p>

<%= link_to 'Log Out', destroy_insurer_session_path, method: :delete %>

app/views/static_pages/home.html.erb
   <!-- Preloader -->
    
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
                <div class="top-left-part"><a class="logo" href="<%=root_path%>"><b><%= image_tag('hiisafrica-xx.png', alt: 'Logo')%></b><span class="hidden-xs"><strong>HIIS </strong></span></a></div>
                <ul class="nav navbar-top-links navbar-left hidden-xs">
                    <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="icon-arrow-left-circle ti-menu"></i></a></li>
                   
                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">


                    <li class="dropdown"> <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><i class="icon-person">Menu</i>
          <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
          </a>
                        <ul class="dropdown-menu mailbox animated bounceInDown">
                            <li>
                                <a href="#"> About HIIS </a>
                            </li>
                            <li>
                                <a href="#">Contact Us </a>
                                
                            </li>
                            <hr/>
                            <li> <a href="#">Request A Demo </a></li>
                           
                        </ul>
                        
                    </li>
                    <!-- /.dropdown -->
                   
                    <li class="dropdown">


                        <% if insurer_signed_in? %>
                                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <%=user_avatar(current_insurer, alt: 'user-img', class: 'img-circle', width: '36')%><b class="hidden-xs">
                                <%= current_insurer.company_name %>

                        <% elsif provider_signed_in? %>
                                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <%=user_avatar(current_provider, alt: 'user-img', class: 'img-circle', width: '36')%> <b class="hidden-xs">
                             <%= current_provider.company_name %>
                        <% else %>
                            <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <b class="hidden-xs">
                            
                        <% end %>
                        
                        </b> </a>
                        <ul class="dropdown-menu dropdown-user animated flipInY">
                        	<% if provider_signed_in? %>
                        	 <li><a href="<%=provider_dashboard_path%>"><i class="ti-box"></i>  Dashboard</a></li> <hr/>

                        	 <% elsif  insurer_signed_in? %>
                        	 <li><a href="<%=insurer_dashboard_path%>"><i class="ti-box"></i>  Dashboard</a></li> <hr/>
                        	 <% else %>
                        	 <li><a href="<%=new_provider_registration_path%>"><i class="ti-box"></i>  Sign Up</a></li> <hr/>

                        	 <% end %>
                        	 	
                            <li><a href="javascript:void(0)"><i class="ti-user"></i>  My Profile</a></li>
                           

                             <% if insurer_signed_in? %>
                                <li><a href="<%=edit_insurer_registration_path%>"><i class="ti-settings"></i>  Account Setting</a></li>

                            <% elsif provider_signed_in? %>
                                 <li><a href="<%=edit_provider_registration_path%>"><i class="ti-settings"></i>  Account Setting</a></li>
                            <% else %>
                                 <li><a href="#"><i class="ti-settings"></i>  Account Management</a></li>
                            <% end %>


                              <% if insurer_signed_in? %>
                            <li><a href="<%=destroy_insurer_session_path%>" data-method="delete"><i class="fa fa-power-off"></i> Logout</a></li>
                            <% elsif provider_signed_in? %>
                             <li><a href="<%=destroy_provider_session_path%>" data-method="delete"><i class="fa fa-power-off"></i> Logout</a></li>
                             <% else %>
                              <li><a href="#" data-method="delete"><i class="fa fa-power-off"></i> Logout</a></li>
                            <% end %>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- <li class="right-side-toggle"> <a class="waves-effect waves-light" href="javascript:void(0)"><i class="ti-settings"></i></a></li> -->
                    <!-- /.dropdown -->
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
       









        <div id="page-wrapper" style="margin: 0px;">
            <div class="container-fluid">
                <!-- <div class="row bg-title">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <h4 class="page-title" style="text-align: center;">Heath Insurance Management Systems</h4>
                    </div>
                    <div class="col-lg-6 col-sm-12 col-md-6 col-xs-12">
                       
                    </div>
                    -->
                </div> 
                <div class="row">
                    <div class="col-sm-12">
                        <div class="white-box">
                            <h3 class="box-title" style="text-align: center;">Welcome to HIIS</h3>

                            <p style="text-align: center;"> HIIS is an innovative health insurance  management system. </p>
                            <hr/>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="card" style="text-align: center; margin: 20px;">
                                        <i class="fa fa-users fa-5x" style="font-size: 50px; color: green; margin: 30px;"> </i>
                                        <div class="card-block">
                                            <h4 class="card-title">Health Insurer</h4>
                                            <p class="card-text">Click Below to Login</p>
                                            <a href="<%=new_insurer_session_path%>" class="btn btn-success btn-lg " data-disable-with="Please wait ..."> <i class="fa fa-power-off "></i>  LOG IN NOW</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="card" style="text-align: center; margin: 20px;">
                                         <i class="fa fa-medkit fa-5x " style="font-size: 50px; color: green; margin: 30px;"> </i>
                                        <div class="card-block">
                                            <h4 class="card-title">Health Service Provider</h4>
                                            <p class="card-text">Click Here to Login as a Health Service Provider</p>
                                            <a href="<%=new_provider_session_path%>" class="btn btn-primary btn-lg " data-disable-with="Please wait ..."><i class="fa fa-power-off "></i> LOG ME IN</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center" style="left: 0px;"> 2018 &copy;  HIIS </footer>
        </div>
        <!-- /#page-wrapper -->