config/routes.rb
Rails.application.routes.draw do
  



  root 'static_pages#home'


get 'provider/dashboard/panelist', to: 'provider/dashboard#panelist', as: 'provider_panelist'
get 'provider/dashboard/panelist/view_enrolee/:enrolee_id', to: 'provider/dashboard#view_provider_enrolee', as: 'view_provider_enrolee'


get 'enrolees/:enrolee_id/show_dependants_group', to: 'insurer/enrolees#show_dependants', as: 'show_dependants_group'

namespace :provider do 

  resources :claims do 
    member do 
        get 'addService'
        get 'preview'
        get 'submit'
    end
  end
end
  
  get 'provider/enrolees/panelist', to: 'provider#enrolees', as: 'provider_enrolees'
  get 'insurer/enrolees/quicksearch', to: 'insurer/enrolees#quicksearch', as: 'insurer_enrolees_quicksearch'
  get 'insurer/enrolees/data_upload', to: 'insurer/enrolees#data_upload', as: 'insurer_enrolees_data_upload'
  get 'insurer/dependants/data_upload', to: 'insurer/dependants#data_upload', as: 'insurer_dependants_data_upload'
  post 'insurer/enrolees/populatedb', to: 'insurer/enrolees#populatedb', as: 'insurer_enrolees_populatedb'
  post 'insurer/dependants/populatedb', to: 'insurer/dependants#populatedb', as: 'insurer_dependants_populatedb'

namespace :insurer do 
  resources :enrolees do 
    member do 
      get 'addDependant'
      get 'preview'
    end

  end
  resources :plans
  resources :companies
  resources :dependants
  resources :claims do
    member do  
      get 'addService'
      get 'submit'
      get 'preview'
      get 'vet'
      post 'submit_vetted'
      get 'invoice_generation'
    end
  end
end


  resources :services
  
  devise_for :providers, path: 'providers', controllers: {sessions: 'providers/sessions', registrations: 'providers/registrations'}
  devise_for :insurers, path: 'insurers', controllers: { sessions: 'insurers/sessions', registrations: 'insurers/registrations'}


  #static pages routes
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'

  get 'claims/invoice/generate_pdf', to: 'insurer/claims#generate_invoice', as: 'generate_claim_invoice_pdf'



  # Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  #dashboard pages

  get 'insurer/dashboard/index', to: 'insurer/dashboard#index', as: 'insurer_dashboard'

  get 'provider/dashboard/index', to: 'provider/dashboard#index', as: 'provider_dashboard'
    
  get 'static_pages/dashboard', to: 'static_pages#dashboard', as: 'dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/insurer/claims_controller.rb
class Insurer::ClaimsController < ApplicationController


  include ApplicationHelper

  before_action :set_claim, only: [:show, :edit, :update, :destroy, :preview, :invoice_generation, :submit]

  layout 'dashboard'

  # GET /claims
  # GET /claims.json

  before_action :authenticate_insurer!, only: [:index, :edit]

  require 'rubyXL'

  def index
    if params[:filter] == 'pending'
        @filter = 'pending'
      @claims = current_insurer.claims.where(status: 1).order("created_at desc")
    elsif params[:filter] == 'vetted'
        @filter = 'vetted'
        @claims = current_insurer.claims.where(status: 2).order("created_at desc")
    elsif params[:filter] == 'rejected'
        @filter = 'rejected'
        @claims = current_insurer.claims.where(status: 3).order("created_at desc")
    else
      @filter = 'all'
      @claims = current_insurer.claims.all.order("created_at desc")
    end


  end

  # GET /claims/new
  def new
    @claim = current_insurer.claims.new   
   
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = current_insurer.claims.build(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to addService_insurer_claim_path(id: @claim.id), notice: 'Claim was successfully created.' }
        format.json 
      else
        format.html { render :new }
        format.json 
      end
    end
  end

  def addService
    @claim = Claim.find(params[:id])
    @drug_list_options = get_drug_list_options
    @service_list_options = get_service_list_options

    #generating a new claim number
      new_claim_no = generate_claim_code(@claim)
      @claim.update(claim_no: new_claim_no)
  end
  




  def vet
    claim_id = params[:claim_id]
    @claim = current_insurer.claims.find(claim_id)
     @attachment_count = @claim.attachments.count


  end

  def submit_vetted
    claim = current_insurer.claims.find(params[:claim_id])
    service_count = claim.services.count

    params.keys.each do |param|
      if param.include?('vc')
          id = param.split('-').second.to_i
          service  = claim.services.find(id)
          service.update(vetted_cost: params[param])
      end
    end


    #updated vetted_total
    vetted_total = params[:vetted_total]
    insurer_comment = params[:insurer_comment]

    if claim.update(authorized_amount: vetted_total, status: 2, insurer_comment: insurer_comment)
      flash[:success] = 'This claim was vetted successfully'
      redirect_to invoice_generation_insurer_claim_path
    else
      flash[:error] = 'An error occured when vetting this claim amounts. please try again'
      redirect_to vet_insurer_claim_path
    end

  end

  # def auto_vetting

  #    claim_id = params[:claim_id]
  #   @claim = current_insurer.claims.find(claim_id)
  #    @attachment_count = @claim.attachments.count

  #         drug_list_workbook = RubyXL::Parser.parse("druglist.xlsx")
  #         service_list_workbook = RubyXL::Parser.parse("servicex.xlsx")

  #         drug_list_worksheet = drug_list_workbook.worksheets[0]
  #         service_list_worksheet = service_list_workbook[0]

  #         recommended_costs = []

  #         @claim.services.each do |service|

  #           if service.type == "DRUG"
  #              drug_list_worksheet.each do |row|
  #                 if !row[1].nil? #checking if the second column(1) of row is nil . remember reading starts from 0
  #                   val = row[1].value.to_s
  #                   if val == service.name 
  #                       recommended_costs[service.id] = row[2]
  #                       option = "#{'<option value='+val+'>' + val + '</option>'}"

  #                       options << option #add the new option tag to the options variable
  #                 end
                    

  #               end
  #             requested_cost = service.cost

              
  #             recommended_cost

  #        end




  # end

  # GET /claims/1
  # GET /claims/1.json
  def show
     @attachment_count = @claim.attachments.count

  end

  def invoice_generation


  end

  def generate_invoice
    @claim = Claim.find(params[:claim_id])

    respond_to do |format|
          format.html
          format.pdf do


             render pdf:  "claim_invoice_MFN/2018/CLM/1000#{@claim.id}",
               template:     'insurer/claims/generate_invoice.html.erb',
               layout:       'layouts/invoice',
               title:        "Download invoice",
               show_as_html: false,
               margin: { top: 10, bottom: 10 },
               background: true
          end
    end
  end

  

  # GET /claims/1/edit
  def edit
  end


  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
 def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js { render 'addService' }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to insurer_claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    check_services(@claim)
     @attachment_count = @claim.attachments.count

  end


   def submit
    
    check_services(@claim)

    total_requested_cost = total_claim_cost(@claim)
    if @claim.update(status: 1, total_requested_amount: total_requested_cost)
       flash[:success] = 'Successfully submitted claim for Vetting'
       redirect_to insurer_claims_path
    else
      flash[:error] =  'There was an error submitting this claim. please try again or contact your IT desk'
      redirect_to preview_insurer_claim_path(@claim) 
    end
   
  end


private
    # Use callbacks to share common setup or constraints between actions.
 
    def check_services(claim)
      if claim.services.count < 1 
        flash[:error] = "Kindly add a service to this claim to continue"
        redirect_to addService_insurer_claim_path(claim)
      end

    end

    def get_drug_list_options 


      print Rails.root.join('druglist.xlsx')
      drug_list_workbook = RubyXL::Parser.parse("druglist.xlsx")

      drug_list_worksheet = drug_list_workbook.worksheets[0]

      options = ""


      drug_list_worksheet.each do |row|
        if !row[1].nil? #checking if the second column(1) of row is nil . remember reading starts from 0
          val = row[1].value.to_s
              option = "#{'<option value='+val+'>' + val + '</option>'}"

              options << option #add the new option tag to the options variable
        end
          

      end

      options

  end



  def get_service_list_options 

    print Rails.root.join('servicex.xlsx')
    service_list_workbook = RubyXL::Parser.parse("servicex.xlsx")

    service_list_worksheet = service_list_workbook.worksheets[0]

    options = ""


      service_list_worksheet.each do |row|
        if !row[2].nil?
          val = row[2].value.to_s
          option = "#{'<option value='+val+'>' + val + '</option>'}"

              options << option
        end
          

      end

      options

end


def generate_claim_code(claim)

    claim_id = claim.id.to_s
    claim_year = claim.created_at.year.to_s

    a = current_insurer.company_name.split(' ').first[0,1]
    b = current_insurer.company_name.split(' ').second[0,1]
    c = current_insurer.company_name.split(' ').third

    if !c.nil?
      c = c[0,1]

      claim_code = "#{a+b+c}/#{claim_year}/CLM/000#{claim_id}"
    else
      claim_code = "#{a+b}/#{claim_year}/CLM/000#{claim_id}"
    end

    claim_code

end




def set_claim
  @claim = Claim.find(params[:id])
end






    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:facility_name, :date, :authorization_number, :total_requested_amount, :authorized_amount, :rejected_amount, :authority_name, :provider_id, :authority_designation, :member_number, :member_name, :status, :insurer_id)
    end

end

app/controllers/insurer/companies_controller.rb
class Insurer::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]


  layout 'dashboard'
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to insurer_companies_path, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to insurer_companies_path, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to insurer_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address, :plan, :contact, :insurer_id)
    end
end

app/controllers/insurer/dashboard_controller.rb
class Insurer::DashboardController < ApplicationController

  layout 'dashboard'

  def index
  	   @enrolees = current_insurer.enrolees.limit(10).order('created_at DESC')
  	   @total_claims = current_insurer.claims
  	   @total_enrolees = current_insurer.enrolees
    
  end
end

app/controllers/insurer/dependants_controller.rb
class Insurer::DependantsController < ApplicationController
  before_action :set_dependant, only: [:show, :edit, :update, :destroy]

  # GET /dependants
  # GET /dependants.json
  def index
    @dependants = Dependant.all
  end

  # GET /dependants/1
  # GET /dependants/1.json
  def show
  end

  # GET /dependants/new
  def new (enrolee_id)
    enrolee = Enrolee.find(enrolee_id)
    @dependant = enrolee.dependants.build
  end

  def dependant_card_issued(dependant)

  end

 
  def data_upload
    @insurer = current_insurer

  end

  def populatedb
     @insurer = current_insurer
    file = params[:dependants_list]
    company_name = params[:company_name]
    insurer_id = current_insurer.id

    Dependant.import(file, company_name, insurer_id)

    flash[:success] = "Dependants Data successfully uploaded to database"
    redirect_to insurer_enrolees_path

  end


  # GET /dependants/1/edit
  def edit
  end

  # POST /dependants
  # POST /dependants.json
  def create

    @enrolee = current_insurer.enrolees.find(params[:dependant][:enrolee_id])
    @dependant = @enrolee.dependants.new(dependant_params)

     generate_number = generate_dependant_enrolee_number(@dependant, @enrolee)
     @dependant.enrolee_number = generate_number
   

    respond_to do |format|
      if @dependant.save
        format.html { redirect_to insurer_enrolee_path(@dependant.enrolee), notice: 'Dependant was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  # PATCH/PUT /dependants/1
  # PATCH/PUT /dependants/1.json
  def update
    respond_to do |format|
      if @dependant.update(dependant_params)
        format.html { redirect_to insurer_enrolee_path(@dependant.enrolee), notice: 'Dependant was successfully updated.' }
        format.json { render :show, status: :ok, location: @dependant }
      else
        format.html { render :edit }
        format.json { render json: @dependant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependants/1
  # DELETE /dependants/1.json
  def destroy
    @enrolee = @dependant.enrolee
    @dependant.destroy
    respond_to do |format|
      format.html { redirect_to insurer_dependants_url, notice: 'Dependant was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependant
      @dependant = Dependant.find(params[:id])
    end


    def generate_dependant_enrolee_number(dependant, enrolee)


      e_number = enrolee.enrolee_number

      if dependant.dependant_type == "spouse"
        d_number = e_number + 'S'
      elsif dependant.dependant_type == "child"
        child_dependants = enrolee.dependants.where(dependant_type: 'child')
        if child_dependants.any?
          child_count = child_dependants.count 
          new_count = child_count+1
          new_count = new_count.to_s
        else
          new_count = 1.to_s
        end

        d_number = e_number+"C"+new_count

      else 
        puts "Unrecognized dependant type"

      end
      puts d_number
      d_number
     

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependant_params
      params.require(:dependant).permit(:surname, :firstname, :dependant_type, :middlename, :dob, :sex, :blood_group, :primary_hospital, :secondary_hospital, :genotype, :photo, :enrolee_id, :insurer_id)
    end
end

app/controllers/insurers/confirmations_controller.rb
class Insurers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/helpers/dependants_helper.rb
module DependantsHelper
end

app/views/insurer/dependants/_form.html.erb
<%= form_with(model: dependant, url: insurer_dependants_path, local: true) do |form| %>
  <% if dependant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dependant.errors.count, "error") %> prohibited this dependant from being saved:</h2>

      <ul>
      <% dependant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :dependant_surname %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :dependant_firstname %>
  </div>

  <div class="field">
    <%= form.label :middlename %>
    <%= form.text_field :middlename, id: :dependant_middlename %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.datetime_select :dob, id: :dependant_dob %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :dependant_sex %>
  </div>

  <div class="field">
    <%= form.label :blood_group %>
    <%= form.text_field :blood_group, id: :dependant_blood_group %>
  </div>

  <div class="field">
    <%= form.label :primary_hospital %>
    <%= form.text_field :primary_hospital, id: :dependant_primary_hospital %>
  </div>

  <div class="field">
    <%= form.label :secondary_hospital %>
    <%= form.text_field :secondary_hospital, id: :dependant_secondary_hospital %>
  </div>

  <div class="field">
    <%= form.label :genotype %>
    <%= form.text_field :genotype, id: :dependant_genotype %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :dependant_photo %>
  </div>

  <div class="field">
    <%= form.label :enrolee.references %>
    <%= form.text_field :enrolee.references, id: :dependant_enrolee.references %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/insurer/dependants/_list.html.erb
                                    <% counter = 1 %>
                                    <% @enrolee.dependants.each do |dependant| %>
                                        <tr>
                                            <th scope="row"><%= counter %></th>
                                            <td><%=dependant.surname%></td>
                                            <td><%= dependant.firstname%></td>
                                            <td><%= dependant.middlename%></td>
                                            <td><%= dependant.enrolee_number %></td>
                                            
                                            <td><%=dependant.dependant_type%></td>
                                            <td><%= dependant.dob%></td>
                                            <td>
                                                <% if dependant.card_issued %>
                                                <span class="badge badge-success">Yes </span>

                                                <% else %>
                                                <span class="badge badge-default">No </span>
                                               

                                                <% end %>
                                             </td>
                                            <td>
                                            
                                           
                                            
                                          <%= form_for(@enrolee.dependants.find(dependant.id), url: insurer_dependant_path(dependant), html: {method: :delete}, remote: true ) do |f| %>
                                          
                                            <button type="submit" class='fa fa-trash m-r-5' style="color: red;" data-confirm="Are you sure? This dependant will be removed from list"></button>


                                            <% end %>
                                             
                                            
                                            
                                            </td>
                                        </tr>
                                        <% counter += 1%>
                                        <% end %>

app/views/insurer/dependants/create.js.erb
$("#dependants_list").html("<%= escape_javascript(render('insurer/dependants/list')) %>");
$("#dependantsModal").modal("hide");
toastr.success('New Dependant Details Added to Enrolee', 'Success');

app/views/insurer/dependants/data_upload.html.erb
 <%= render 'layouts/shared/nav' %>
 <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Upload Dependants Data</h4> </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="#"><%=current_insurer.company_name%></a></li>
                            <li class="active">DATA Upload</li>
                        </ol>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="white-box">

                           

                    <div class="row">
                  
                    <div class="col-md-12">
                        <div class="panel panel-success">
                            <div class="panel-heading">Excel, csv dependants data upload
                            </div>
                            <div class="panel-body">
                            <span class="badge info" id="notification"></span>
                            
                            <h2> See format Below</h2>

                            <table class="table table-responsive table-condensed">
                                <tr>
                                    <th>Company Name </th>
                                    <th>Surname </th>
                                    <th>Firstname </th>
                                    <th>Middle Name </th>
                                    <th>Enrolee Number </th>
                                     <th>Principal Number</th>
                                    <th>Primary Hospital</th>
                                    <th>Phone </th>
                                    <th>Date of Birth</th>
                                    <th>Sex </th>
                                    <th>Location(state)</th>
                                    <th>ID card issued </th>
                                    

                                </tr>

                                <tr>
                                    <td> A  </td>
                                    <td> B  </td>
                                    <td> C  </td>
                                    <td> D  </td>
                                    <td> E  </td>
                                    <td> F  </td>
                                    <td> G  </td>
                                    <td> H  </td>
                                    <td> I  </td>
                                    <td> J  </td>
                                    <td> K  </td>
                                    <td> L  </td>
                                    <td> M  </td>

                                </tr>

                            </table>

                             <br/>
                            <hr/>
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                     Data Upload Section 
                                </div>

                                <div class="panel-body">

                                            <%=form_tag insurer_dependants_populatedb_path, multipart:true do %>
                                           
                                                <div class="row">
                                                 <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <select name="company_name" class="form-control">
                                                                <% current_insurer.companies.each do |company| %>
                                                                 <option value="<%=company.name%>"><%=company.name%></option>
                                                                <% end %>
                                                                
                                                            </select>

                                                        </div>

                                                </div>
                                                </div>

                                                <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">

                                                    <label>Upload Dependants List</label>
                                                    <%= file_field_tag :dependants_list, class: 'form-control', required: true %>
                                                   <br/>


                                            <%= submit_tag "Upload Data", class: 'btn btn-lg btn-primary pull-right', 'data-disable-with': 'Uploading Data (please wait...)' %>
                                           


                                                   

                                                </div>
                                            </div>
                                           </div>

                                            <% end %>
                                </div>

                                <div class="panel-footer">


                                </div>
                            </div>




                                    





                            </div>
                        </div>
                       
                    </div>
                </div>





        

                        </div>
                    </div>
                </div>
               
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2018 &copy; HIIS </footer>
        </div>
        <!-- /#page-wrapper -->

app/views/insurer/dependants/destroy.js.erb
$("#dependants_list").html("<%= escape_javascript(render('insurer/dependants/list')) %>");
$("#notification2").html('- Removed Successfully');
toastr.warning("Dependant removed from Enrolee Record", "Deleted!");

app/views/insurer/dependants/edit.html.erb
<h1>Editing Dependant</h1>

<%= render 'form', dependant: @dependant %>

<%= link_to 'Show', insurer_dependant_path(@dependant) %> 

app/views/insurer/dependants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependants</h1>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Dob</th>
      <th>Sex</th>
      <th>Blood group</th>
      <th>Primary hospital</th>
      <th>Secondary hospital</th>
      <th>Genotype</th>
      <th>Photo</th>
      <th>Enrolee.references</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependants.each do |dependant| %>
      <tr>
        <td><%= dependant.surname %></td>
        <td><%= dependant.firstname %></td>
        <td><%= dependant.middlename %></td>
        <td><%= dependant.dob %></td>
        <td><%= dependant.sex %></td>
        <td><%= dependant.blood_group %></td>
        <td><%= dependant.primary_hospital %></td>
        <td><%= dependant.secondary_hospital %></td>
        <td><%= dependant.genotype %></td>
        <td><%= dependant.photo %></td>
        <td><%= dependant.enrolee.references %></td>
        <td><%= link_to 'Show', insurer_dependant_path(dependant) %></td>
        <td><%= link_to 'Edit', edit_insurer_dependant_path(dependant) %></td>
        <td><%= link_to 'Destroy', insurer_dependant_path(dependant), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependant', new_insurer_dependant_path %>

app/views/insurer/dependants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @dependant.surname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @dependant.firstname %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @dependant.middlename %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dependant.dob %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @dependant.sex %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @dependant.blood_group %>
</p>

<p>
  <strong>Primary hospital:</strong>
  <%= @dependant.primary_hospital %>
</p>

<p>
  <strong>Secondary hospital:</strong>
  <%= @dependant.secondary_hospital %>
</p>

<p>
  <strong>Genotype:</strong>
  <%= @dependant.genotype %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @dependant.photo %>
</p>

<p>
  <strong>Enrolee.references:</strong>
  <%= @dependant.enrolee.references %>
</p>

<%= link_to 'Edit', edit_dependant_path(@dependant) %> |
<%= link_to 'Back', dependants_path %>