config/routes.rb
Rails.application.routes.draw do
  



  root 'static_pages#home'


get 'provider/dashboard/panelist', to: 'provider/dashboard#panelist', as: 'provider_panelist'
get 'provider/dashboard/panelist/view_enrolee/:enrolee_id', to: 'provider/dashboard#view_provider_enrolee', as: 'view_provider_enrolee'


get 'enrolees/:enrolee_id/show_dependants_group', to: 'insurer/enrolees#show_dependants', as: 'show_dependants_group'

namespace :provider do 

  resources :claims do 
    member do 
        get 'addService'
        get 'preview'
        get 'submit'
    end
  end
end
  
  get 'provider/enrolees/panelist', to: 'provider#enrolees', as: 'provider_enrolees'
  get 'insurer/enrolees/quicksearch', to: 'insurer/enrolees#quicksearch', as: 'insurer_enrolees_quicksearch'
  get 'insurer/enrolees/data_upload', to: 'insurer/enrolees#data_upload', as: 'insurer_enrolees_data_upload'
  get 'insurer/dependants/data_upload', to: 'insurer/dependants#data_upload', as: 'insurer_dependants_data_upload'
  post 'insurer/enrolees/populatedb', to: 'insurer/enrolees#populatedb', as: 'insurer_enrolees_populatedb'
  post 'insurer/dependants/populatedb', to: 'insurer/dependants#populatedb', as: 'insurer_dependants_populatedb'

namespace :insurer do 
  resources :enrolees do 
    member do 
      get 'addDependant'
      get 'preview'
    end

  end
  resources :plans
  resources :companies
  resources :dependants
  resources :claims do
    member do  
      get 'addService'
      get 'submit'
      get 'preview'
      get 'vet'
      post 'submit_vetted'
      get 'invoice_generation'
    end
  end
end


  resources :services
  
  devise_for :providers, path: 'providers', controllers: {sessions: 'providers/sessions', registrations: 'providers/registrations'}
  devise_for :insurers, path: 'insurers', controllers: { sessions: 'insurers/sessions', registrations: 'insurers/registrations'}


  #static pages routes
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'

  get 'claims/invoice/generate_pdf', to: 'insurer/claims#generate_invoice', as: 'generate_claim_invoice_pdf'



  # Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  #dashboard pages

  get 'insurer/dashboard/index', to: 'insurer/dashboard#index', as: 'insurer_dashboard'

  get 'provider/dashboard/index', to: 'provider/dashboard#index', as: 'provider_dashboard'
    
  get 'static_pages/dashboard', to: 'static_pages#dashboard', as: 'dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/concerns/claims.rb
module ClaimsTotal
    extend ActiveSupport::Concern

    def total_claim_cost(claim)
        total_cost = 0
        claim.services.each do |service|
            service_unit_cost = service.cost
            qty  = service.qty
            service_total_cost = service_unit_cost * qty
            total_cost += service_total_cost
        end

        total_cost

    end
  end

app/controllers/insurer/claims_controller.rb
class Insurer::ClaimsController < ApplicationController


  include ApplicationHelper

  before_action :set_claim, only: [:show, :edit, :update, :destroy, :preview, :invoice_generation, :submit]

  layout 'dashboard'

  # GET /claims
  # GET /claims.json

  before_action :authenticate_insurer!, only: [:index, :edit]

  require 'rubyXL'

  def index
    if params[:filter] == 'pending'
        @filter = 'pending'
      @claims = current_insurer.claims.where(status: 1).order("created_at desc")
    elsif params[:filter] == 'vetted'
        @filter = 'vetted'
        @claims = current_insurer.claims.where(status: 2).order("created_at desc")
    elsif params[:filter] == 'rejected'
        @filter = 'rejected'
        @claims = current_insurer.claims.where(status: 3).order("created_at desc")
    else
      @filter = 'all'
      @claims = current_insurer.claims.all.order("created_at desc")
    end


  end

  # GET /claims/new
  def new
    @claim = current_insurer.claims.new   
   
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = current_insurer.claims.build(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to addService_insurer_claim_path(id: @claim.id), notice: 'Claim was successfully created.' }
        format.json 
      else
        format.html { render :new }
        format.json 
      end
    end
  end

  def addService
    @claim = Claim.find(params[:id])
    @drug_list_options = get_drug_list_options
    @service_list_options = get_service_list_options

    #generating a new claim number
      new_claim_no = generate_claim_code(@claim)
      @claim.update(claim_no: new_claim_no)
  end
  




  def vet
    claim_id = params[:claim_id]
    @claim = current_insurer.claims.find(claim_id)
     @attachment_count = @claim.attachments.count


  end

  def submit_vetted
    claim = current_insurer.claims.find(params[:claim_id])
    service_count = claim.services.count

    params.keys.each do |param|
      if param.include?('vc')
          id = param.split('-').second.to_i
          service  = claim.services.find(id)
          service.update(vetted_cost: params[param])
      end
    end


    #updated vetted_total
    vetted_total = params[:vetted_total]
    insurer_comment = params[:insurer_comment]

    if claim.update(authorized_amount: vetted_total, status: 2, insurer_comment: insurer_comment)
      flash[:success] = 'This claim was vetted successfully'
      redirect_to invoice_generation_insurer_claim_path
    else
      flash[:error] = 'An error occured when vetting this claim amounts. please try again'
      redirect_to vet_insurer_claim_path
    end

  end

  # def auto_vetting

  #    claim_id = params[:claim_id]
  #   @claim = current_insurer.claims.find(claim_id)
  #    @attachment_count = @claim.attachments.count

  #         drug_list_workbook = RubyXL::Parser.parse("druglist.xlsx")
  #         service_list_workbook = RubyXL::Parser.parse("servicex.xlsx")

  #         drug_list_worksheet = drug_list_workbook.worksheets[0]
  #         service_list_worksheet = service_list_workbook[0]

  #         recommended_costs = []

  #         @claim.services.each do |service|

  #           if service.type == "DRUG"
  #              drug_list_worksheet.each do |row|
  #                 if !row[1].nil? #checking if the second column(1) of row is nil . remember reading starts from 0
  #                   val = row[1].value.to_s
  #                   if val == service.name 
  #                       recommended_costs[service.id] = row[2]
  #                       option = "#{'<option value='+val+'>' + val + '</option>'}"

  #                       options << option #add the new option tag to the options variable
  #                 end
                    

  #               end
  #             requested_cost = service.cost

              
  #             recommended_cost

  #        end




  # end

  # GET /claims/1
  # GET /claims/1.json
  def show
     @attachment_count = @claim.attachments.count

  end

  def invoice_generation


  end

  def generate_invoice
    @claim = Claim.find(params[:claim_id])

    respond_to do |format|
          format.html
          format.pdf do


             render pdf:  "claim_invoice_MFN/2018/CLM/1000#{@claim.id}",
               template:     'insurer/claims/generate_invoice.html.erb',
               layout:       'layouts/invoice',
               title:        "Download invoice",
               show_as_html: false,
               margin: { top: 10, bottom: 10 },
               background: true
          end
    end
  end

  

  # GET /claims/1/edit
  def edit
  end


  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
 def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js { render 'addService' }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to insurer_claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    check_services(@claim)
     @attachment_count = @claim.attachments.count

  end


   def submit
    
    check_services(@claim)

    total_requested_cost = total_claim_cost(@claim)
    if @claim.update(status: 1, total_requested_amount: total_requested_cost)
       flash[:success] = 'Successfully submitted claim for Vetting'
       redirect_to insurer_claims_path
    else
      flash[:error] =  'There was an error submitting this claim. please try again or contact your IT desk'
      redirect_to preview_insurer_claim_path(@claim) 
    end
   
  end


private
    # Use callbacks to share common setup or constraints between actions.
 
    def check_services(claim)
      if claim.services.count < 1 
        flash[:error] = "Kindly add a service to this claim to continue"
        redirect_to addService_insurer_claim_path(claim)
      end

    end

    def get_drug_list_options 


      print Rails.root.join('druglist.xlsx')
      drug_list_workbook = RubyXL::Parser.parse("druglist.xlsx")

      drug_list_worksheet = drug_list_workbook.worksheets[0]

      options = ""


      drug_list_worksheet.each do |row|
        if !row[1].nil? #checking if the second column(1) of row is nil . remember reading starts from 0
          val = row[1].value.to_s
              option = "#{'<option value='+val+'>' + val + '</option>'}"

              options << option #add the new option tag to the options variable
        end
          

      end

      options

  end



  def get_service_list_options 

    print Rails.root.join('servicex.xlsx')
    service_list_workbook = RubyXL::Parser.parse("servicex.xlsx")

    service_list_worksheet = service_list_workbook.worksheets[0]

    options = ""


      service_list_worksheet.each do |row|
        if !row[2].nil?
          val = row[2].value.to_s
          option = "#{'<option value='+val+'>' + val + '</option>'}"

              options << option
        end
          

      end

      options

end


def generate_claim_code(claim)

    claim_id = claim.id.to_s
    claim_year = claim.created_at.year.to_s

    a = current_insurer.company_name.split(' ').first[0,1]
    b = current_insurer.company_name.split(' ').second[0,1]
    c = current_insurer.company_name.split(' ').third

    if !c.nil?
      c = c[0,1]

      claim_code = "#{a+b+c}/#{claim_year}/CLM/000#{claim_id}"
    else
      claim_code = "#{a+b}/#{claim_year}/CLM/000#{claim_id}"
    end

    claim_code

end




def set_claim
  @claim = Claim.find(params[:id])
end






    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:facility_name, :date, :authorization_number, :total_requested_amount, :authorized_amount, :rejected_amount, :authority_name, :provider_id, :authority_designation, :member_number, :member_name, :status, :insurer_id)
    end

end

app/controllers/provider/claims_controller.rb
class Provider::ClaimsController < ApplicationController
  
  include ApplicationHelper

  before_action :set_claim, only: [:show, :edit, :update, :destroy, :preview, :submit]

  
  layout 'dashboard'
  # GET /claims
  # GET /claims.json

  before_action :authenticate_provider!, only: [:new, :edit]

  require 'rubyXL'

  def index
    if params[:filter] == 'pending'
      @claims = Claim.where(status: 0).order("created_at desc")
    else
      @claims = Claim.all.order("created_at desc")
    end
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
     @attachment_count = @claim.attachments.count
  end

  # GET /claims/new
  def new
    if params[:enrolee_id]
      @enrolee = Enrolee.find_by_id(params[:enrolee_id])
      @claim = Claim.new
    else
      @enrolee = nil
      @claim = Claim.new
    end
   
    # service_list_workbook = RubyXL::Parser.parse("../asset/files/service_list.xlsx")
    # service_list_worksheet = service_list_workbook.worksheets[0]

  end

  def addService
    @claim = Claim.find(params[:id])
    @drug_list_options = get_drug_list_options
    @service_list_options = get_service_list_options


    #generating a new claim number
      new_claim_no = generate_claim_code(@claim)
      @claim.update(claim_no: new_claim_no)

  end

  # GET /claims/1/edit
  def edit
  end


  # POST /claims
  # POST /claims.json
  def create
    @claim = current_provider.claims.build(claim_params)
    respond_to do |format|
      if @claim.save
        format.html { redirect_to addService_provider_claim_path(id: @claim.id), notice: 'Claim was successfully created.' }
        format.json 
      else
        format.html { render :new }
        format.json 
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js { render 'addService' }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to provider_claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    check_services(@claim)
    @attachment_count = @claim.attachments.count
  end

  def submit
    
    check_services(@claim)

    total_requested_cost = total_claim_cost(@claim)
    if @claim.update(status: 1, total_requested_amount: total_requested_cost)
       flash[:notice] = 'Successfully submitted claim to Insurer'
       redirect_to provider_claims_path
    else
      flash[:error] =  'There was an error submitting this claim. please try again or contact your IT desk'
      redirect_to preview_provider_claim_path(@claim) 
    end
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
 
    def check_services(claim)
      if claim.services.count < 1 
        flash[:error] = "Kindly add a service to this claim to continue"
        redirect_to addService_provider_claim_path(claim)
      end

    end

    def get_drug_list_options 


      print Rails.root.join('druglist.xlsx')
      drug_list_workbook = RubyXL::Parser.parse("druglist.xlsx")

      drug_list_worksheet = drug_list_workbook.worksheets[0]

      options = ""


      drug_list_worksheet.each do |row|
        if !row[1].nil? #checking if the second column(1) of row is nil . remember reading starts from 0
          val = row[1].value.to_s
              option = "#{'<option value='+val+'>' + val + '</option>'}"

              options << option #add the new option tag to the options variable
        end
          

      end

      options

  end



  def get_service_list_options 


    print Rails.root.join('servicex.xlsx')
    service_list_workbook = RubyXL::Parser.parse("servicex.xlsx")

    service_list_worksheet = service_list_workbook.worksheets[0]

    options = ""


    service_list_worksheet.each do |row|
      if !row[2].nil?
        val = row[2].value.to_s
        option = "#{'<option value='+val+'>' + val + '</option>'}"

            options << option
      end
        

    end

    options

end




def generate_claim_code(claim)

    claim_id = claim.id.to_s
    claim_year = claim.created_at.year.to_s

    a = claim.insurer.company_name.split(' ').first[0,1]
    b = claim.insurer.company_name.split(' ').second[0,1]
    c = claim.insurer.company_name.split(' ').third

    if !c.nil?
      c = c[0,1]

      claim_code = "#{a+b+c}/#{claim_year}/CLM/000#{claim_id}"
    else
      claim_code = "#{a+b}/#{claim_year}/CLM/000#{claim_id}"
    end

    claim_code

end


def set_claim
  @claim = Claim.find(params[:id])
end


    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:facility_name, :date, :authorization_number, :total_requested_amount, :authorized_amount, :rejected_amount, :authority_name, :provider_id, :authority_designation, :member_number, :member_name, :status, :insurer_id, {attachments: []})
    end
end

app/controllers/providers/confirmations_controller.rb
class Providers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/providers/unlocks_controller.rb
class Providers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/provider/claims/edit.html.erb
<h1>Editing Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

app/views/provider/claims/index.html.erb
    
    <%= render 'layouts/shared/nav' %>
    <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Claims</h4> </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
                        
                    </div>
                </div>

                 <div class="row">
                    <div class="col-lg-12">
                        <div class="white-box">
                            <h3 class="box-title m-b-0">Claim Progress Preview</h3>
                            <p class="text-muted m-b-20"></p>
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Claim NO#</th>
                                            <th>Date</th>
                                            <th>Insurer</th>
                                            <th>Requested(₦)</th>
                                            <th> Approved(₦) </th>
                                            <th>Status</th>
                                            <th>Due</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                     <% @claims.each do |claim| %>
                                        <tr>
                                            <td><a href="<%=provider_claim_path(claim)%>">#<%= claim.claim_no%></a></td>
                                            <td><span class="text-muted"><i class="fa fa-clock-o"></i><%=claim.created_at.strftime("%F")%></span></td>
                                            <td><%=claim.insurer.company_name%></td>
                                            <td>₦<%=total_claim_cost(claim)%></td>
                                            <td>₦<%=claim.authorized_amount%></td>
                                            <td>
                                              <div class="label label-table <%=get_claim_status_code(claim.status)%>"> <%=get_claim_status_text(claim.status)%> </div>
                                            </td>
                                            <td><%=(claim.created_at + (2*7*24*60*60)).strftime("%F")%></td>
                                        </tr>
                                      <% end %>
                                      
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>



               


            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2018 &copy; HIISafrica </footer>
        </div>
        <!-- /#page-wrapper -->

app/views/provider/claims/new.html.erb
 <%= render 'layouts/shared/nav' %>
 <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">New Claim</h4> </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> <a href="#" target="_blank" class="btn btn-info pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light">Need Help?</a>
                        <ol class="breadcrumb">
                            <li><a href="#"><%=current_provider.company_name%></a></li>
                            <li class="active">New Claim</li>
                        </ol>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-12">

                        <div class="white-box">
                    <div class="row">
                  
                  
                        <div class="col-md-12">
                         <div class="pull-right">
                            <h3>
                              <% if @enrolee.nil? %>
                                Creating New Claim

                                <% else %>

                                   Creating claim for  <b>
                                    <%= "#{@enrolee.surname} #{@enrolee.firstname}" %>  </b>
                                    
                                <% end %>
                            </h3>
                        </div>
                    </div>



                    <div class="col-md-12">




                        <div class="panel panel-success">
                            <div class="panel-heading">
                               
                                + STEP 1 [Basic Info]

                            </div>
                            <div class="panel-body">
                            <span class="badge info" id="notification"></span>
                                



                            
                            <%= render 'form', claim: @claim %>






                            </div>
                        </div>
                       
                    </div>
                </div>





        

                        </div>
                    </div>
                </div>
               
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2018 &copy; HIISafrica </footer>
        </div>
        <!-- /#page-wrapper -->

app/views/provider/claims/preview.html.erb
    
    <%= render 'layouts/shared/nav' %>
    <div id="page-wrapper" class="printArea">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Claim Preview</h4> </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
                        <ol class="breadcrumb">
                            <li><a href="#"><%=@claim.provider.company_name%></a></li>
                            <li class="active">Claim Summary</li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="white-box">
                            <h3><b>CLAIM NO</b> <span class="pull-right">#<%= @claim.claim_no%></span></h3>
                            <hr>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="pull-left">
                                        <address>
                                            <h3> &nbsp;<b class="text-danger"><%=@claim.provider.company_name%></b></h3>
                                            <p class="text-muted m-l-5 break-word" style="width:160px; word-wrap:break-word;"><%=@claim.provider.address%></p>
                                            <span class="text-muted"><i class="fa fa-phone"></i> - <%=@claim.provider.phone%></span>
                                        </address>

                                        <br/>
                                        <h5><b class="text-success">Patient/Member No: </b> <b><%=@claim.member_number%></b></h5> <br/>
                                         <h5><b class="text-success">Authorization Code: </b> <b><%=@claim.authorization_number%></b></h5>
                                    </div>
                                    <div class="pull-right text-right">
                                        <address>
                                            <h3>To,</h3>
                                            <h4 class="font-bold"><%=@claim.insurer.company_name%></h4>
                                            <p class="text-muted m-l-30" style="width:160px; word-wrap:break-word;"><%=@claim.insurer.address%>, <br/> <i class="fa fa-phone"></i> - <%=@claim.insurer.phone%></p>
                                            

                                            <p class="m-t-30"><b>Claim Date :</b> <i class="fa fa-calendar"></i> <%=@claim.created_at.to_formatted_s(:long) %></p>
                                            <p><b>Due Date :</b> <i class="fa fa-calendar"></i> <%=(@claim.created_at + (2*7*24*60*60)).to_formatted_s(:long)%></p>
                                        </address>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="table-responsive m-t-40">
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">#</th>
                                                    <th>Item Type</th>
                                                    <th>Item Name</th>
                                                    <th class="text-right">Qty</th>
                                                    <th class="text-right">Charges</th>
                                                    <th class="text-right">Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <% counter = 1 %>
                                            <% @claim.services.each do |service| %>
                                                <tr>
                                                    <td class="text-center"><%=counter%></td>
                                                    <td><%=service.service_type%></td>
                                                    <td><%=service.name%></td>
                                                    <td class="text-right"><%=service.qty%></td>
                                                    <td class="text-right">₦<%=service.cost%></td>
                                                    <td class="text-right">₦<%=total_cost(service)%></td>
                                                </tr>
                                                <% counter +=1 %>
                                              <% end %>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-12">

                                    <br/><br/>
                                    <div class="pull-left">
                                    <code><b>More Details</b></code>
                                    <code> <%=@claim.description%></code>

                                    <hr/>
                                    <% if @claim.attachments.any? %>
                                        <span class="pull-left badge badge-info" style="background-color: #737979;">  <i class="fa fa-file"> </i> <i><%=pluralize(@attachment_count, "file")%> Attached </i></span>
                                    <% else %>
                                     <span class="pull-left badge"> - No Files Attached </span>
                                     <% end %>


                                    </div>
                                    <div class="pull-right m-t-30 text-right">
                                        <p>Sub - Total amount: <%=total_claim_cost(@claim)%></p>
                                        <p>vat (%) : ₦0.0 </p>
                                        <hr>
                                        <h3><b>Total :</b>₦ <%=total_claim_cost(@claim)%> </h3> </div>
                                    <div class="clearfix"></div>
                                    <hr>
                                    <span class="pull-left">
                                        Authorized By: <b><%= @claim.authority_name%></b>,
                                        <i><%=@claim.authority_designation%></i>
                                    </span>

                                    <div class="text-right">
                                        <a href="<%=submit_provider_claim_path(id: @claim.id)%>" class="btn btn-danger" type="submit" data-confirm="Are you sure? once you submit this claim, you won't be able to edit it again." data-disable-with="Preparing claim for submission . . ."> Submit Claim </a>
                                        <button onClick="javascript:window.print();" class="btn btn-default btn-outline" type="button"> <span><i class="fa fa-print"></i> Print</span> </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- .row -->
                <!-- /.row -->
                <!-- .right-sidebar -->
               
                <!-- /.right-sidebar -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> 2018 &copy; HIISafrica </footer>
        </div>
        <!-- /#page-wrapper -->